version: '2'

services:

  # fund-transfer-worker:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     ports:
  #       - 5010:5010
  #     depends_on:
  #       - fund-transfer-account-api
  #       - mongodb
  #       - rabbitmq

  fund-transfer-account-api:
    image: baldini/testacesso
    container_name: fundtransfer-account-api
    ports:
      - 5000:80

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - 'MONGODB_USER=user'
      - 'MONGODB_PASS=password!'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitUsr'
      RABBITMQ_DEFAULT_PASS: 'rabbitPwd'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'

volumes:
  mongodb-data: {}
