version: '3'

services:

  # fund-transfer-worker:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     ports:
  #       - 5010:5010
  #     depends_on:
  #       - fund-transfer-account-api
  #       - fund-transfer-mongo
  #       - fund-transfer-queue
  #       - fund-transfer-elk

  fund-transfer-account-api:
    image: baldini/testacesso
    container_name: fund-transfer-account-api
    ports:
      - "5000:80"
    restart: always

  fund-transfer-mongo:
    image: mongo:4
    container_name: fund-transfer-mongo
    ports:
      - "27017:27017"
    restart: always

  fund-transfer-queue:
    image: rabbitmq:3-management
    container_name: fund-transfer-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  fund-transfer-elk:
    image: sebp/elk
    container_name: fund-transfer-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    stdin_open: true
    tty: true
    restart: always
