version: '3'

services:

  # fund-transfer-api:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     ports:
  #       - 5010:5010
  #     depends_on:
  #       - fund-transfer-mongo
  #       - fund-transfer-queue

  fund-transfer-mongo:
    image: mongo:4
    container_name: fund-transfer-mongo
    ports:
      - "27017:27017"
    restart: always

  fund-transfer-queue:
    image: rabbitmq:3-management
    container_name: fund-transfer-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
